services:
  - type: web
    name: zinc-server
    rootDir: server
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

